-- ORDER BY 
/*
1- Sintaxis 
SELECT FIRST_NAME, LAST_NAME FROM SAKILA.ACTOR WHERE LAST_UPDATE > '2006-02-02' ORDER BY FIRST_NAME
*/

SELECT FIRST_NAME, LAST_NAME FROM SAKILA.ACTOR 
	WHERE LAST_UPDATE > '2006-02-02' 
		ORDER BY FIRST_NAME;

SELECT * FROM SAKILA.ACTOR;

SELECT * FROM SAKILA.ACTOR 
	ORDER BY LAST_UPDATE;

SELECT NAME, CONTINENT, REGION, SURFACEAREA FROM WORLD.COUNTRY 
	ORDER BY SURFACEAREA;

SELECT * FROM SAKILA.ACTOR 
	ORDER BY FIRST_NAME, LAST_NAME;

-- ORDENACION ASCENDENTE Y DESCENDENTE => ASC DESC

-- En esta query la palabra reservada DESC se encuentra junto a LAST_NAME, así que la ordenancion descendente
-- sólo se aplica a LAST_NAME. Se ordena por defecto de forma ascendente usando FIRST_NAME y cuando este se repite, se ordena de
-- forma descendente por LAST_NAME

SELECT * FROM SAKILA.ACTOR 
	ORDER BY FIRST_NAME, LAST_NAME DESC;

-- Si queremos ordenar de forma descendente por el nombre y por el apellido se escribe de esta forma
SELECT * FROM SAKILA.ACTOR 
	ORDER BY FIRST_NAME DESC, LAST_NAME DESC;

SELECT * FROM SAKILA.ACTOR 
	ORDER BY LAST_UPDATE DESC;

SELECT NAME, CONTINENT, REGION, SURFACEAREA FROM WORLD.COUNTRY 
	ORDER BY SURFACEAREA DESC;

-- Order by referenciando columnas por numero y ALIAS
SELECT NAME, CONTINENT, REGION, SURFACEAREA FROM WORLD.COUNTRY 
	ORDER BY 4 DESC;

SELECT NAME AS NOMBRE, CONTINENT, REGION, SURFACEAREA FROM WORLD.COUNTRY 
	ORDER BY NOMBRE DESC;

-- order by con enum

SELECT NAME AS NOMBRE, CONTINENT, REGION, SURFACEAREA FROM WORLD.COUNTRY 
	ORDER BY continent;

SELECT NAME AS NOMBRE, CONTINENT, REGION, SURFACEAREA FROM WORLD.COUNTRY 
	ORDER BY CAST(continent as char);




